# Generated by Django 5.0.7 on 2024-08-18 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_payment_link_alter_payment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='session_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='id cессии'),
        ),
    ]
